### ISSUE TITLE
Store geometries for all places

### ISSUE THREAD

**Issue by riordan** [pelias/whosonfirst#1]
With the [Who's on First](https://github.com/whosonfirst/data) gazetteer, all places are represented as polygons. Take that, Geonames.

In addition to computing the centroid, as we do with administrative boundaries from [Quattroshapes](https://github.com/foursquare/quattroshapes), we should use this opportunity to store the polygons for all shapes imported from WoF.

We can also use this opportunity to compute the bounding box for each polygon, to quickly provide size & scale (which we could potentially do for all OSM ways as well).

**Comment by riordan** [comment]
- [ ] Store geometry of administrative areas (#19)
- [ ] Store roadway geometries
- [ ] Store building geometries
- [ ] Store AOI geometries

**Comment by dianashk** [comment]
Duplicated by pelias/whosonfirst#19
